### PR TITLE
Chrome local Storage: Individual Tab Deletion

### PR DESCRIPTION
**Pull request by agampreetsingh**
Hey!
This PR solves issue #24 ! :)

### CODE REVIEW

**Comment by onaralili** [comment]
Thanks for your contributions! ✌️

**Comment by onaralili** [comment]
Another issue,
If there are many tabs in the list, the wrong tab will be removed.

**Comment by agampreetsingh** [comment]
Yeah, I noticed the same. It was due to the hard- coded indexes. 
I just made a pull request (PR #27)to fix it and also did some minor enhancements.
Happy to contribute :)

**Comment by onaralili** [comment]
> Yeah, I noticed the same. It was due to the hard- coded indexes.
> I just made a pull request (PR #27)to fix it and also did some minor enhancements.
> Happy to contribute :)

Merged! Works great. Thanks 👍

**Pull request merged**
