### PR TITLE
clicking on a search result brings up the relevant tab

### LINKED ISSUE #45: ability to click a search result item to bring that window/tab forward
Commonly, most tab manager extensions will search and allow you to click results to navigate to that tab. That would be handy when I want to find relevant tabs nearby that may not match the initial search result. This function would be handy without having to go to other extensions to search and click it.

### PR DESCRIPTION
**Pull request by yougotwill**
Sorry for another PR. Couldn't help myself when checking the issues.

This fixes https://github.com/onaralili/SplitUp/issues/45. Tested on firefox and chrome.

### CODE REVIEW

**Comment by onaralili** [comment]
thanks for PR

**Comment by yougotwill** [comment]
@onaralili When you have the time can you release a new version of the extension with the changes and publish it please. Thanks 🙏

**Comment by yougotwill** [comment]
> @onaralili When you have the time can you release a new version of the extension with the changes and publish it please. Thanks 🙏

If you do have time please see this PR first before you publish.
https://github.com/onaralili/SplitUp/pull/50

**Comment by onaralili** [comment]
Published on the both platforms! 🥳

**Pull request merged**
